# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class ProjectEuler
  def sum_of_even_value_terms_in_Fibonacci_sequence(upper_limit)

    a   = [1, 2, 1 + 2]
    sum = 2

    while a[2] <= upper_limit
      sum += a[2] if a[2] % 2 == 0
      a.shift
      a[2] = a[0] + a[1]
    end
    sum
  end
end

solver = ProjectEuler.new
puts solver.sum_of_even_value_terms_in_Fibonacci_sequence(4000000)
